# Site settings
title: CCSS
email: info@c-csa.cn
description: > # this means to ignore newlines until "baseurl:"
  The CryptoCurrency Certification Consortium (C4) establishes cryptocurrency
  standards that help ensure a balance of openness &amp; privacy, security &amp;
  usability, and trust &amp; decentralization.
baseurl: "/CCSS" # the subpath of your site, e.g. /blog/
url: "https://dhcn.github.io" # the base hostname & protocol for your site
github_username:  dhcn
logo: CCSS_Logo_Color_Dark.png
org_logo: C4_Color_Dark.png
# Build settings
markdown: kramdown
